### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-mongodb#2]
e.g. one can connect to MongoDB via SSL using something like this:

mongo --ssl --sslCAFile /var/lib/mongo/ca/mongo-ca.crt --sslPEMKeyFile /var/lib/mongo/ca/localhost.pem --sslAllowInvalidHostnames --port 27017 -u username -p 'password' dbname 

Would be nice if the SPM MongoDB agent could use SSL, too.

**Comment by duartealexf** [comment]
Thank you @otisg for creating this issue. MongoDB really enforces use of SSL throughout a cluster deployment for production. I have such a cluster set up and really looking forward to use the spm-agent. The only way I can use it is with SSL options enabled and working. I believe there are many other people that need this as well.

Please take into consideration the official NodeJS MongoDB driver docs for all SSL options: <http://mongodb.github.io/node-mongodb-native/2.2/tutorials/connect/ssl/>.

**Comment by megastef** [comment]
In the config file we can set the settings described in http://mongodb.github.io/node-mongodb-native/2.2/tutorials/connect/ssl/  - see section mongodb/url/sslOptions (support for multiple entries with leading dash with the properties url and optional sslOptions).

Example /etc/spmagent/config:
```
tokens:
  spm: YOUR_SPM_TOKEN
mongodb:  
  url: 
    - url: mongodb://username:password@hostname:27017/products
      sslOptions: 
        server: 
          sslValidate: false
          sslCA : ./ssl/mongodb-ca.crt
          sslKey: ./ssl/localhost.pem
          sslCert: ./ssl/localhost.pem
          sslPass: 10gen
    - url: mongodb://username:password@localhost:27018/admin 

logger:
  level: info
  console: true
```

Release on npm: v1.30.9
